on:
  push:
    branches:
    - master
  pull_request:

name: xbuild

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        components: clippy, rustfmt
    - run: cargo fmt --all -- --check
    - run: cargo clippy --workspace --examples --tests --all-features -- -D warnings
    - run: cargo test

  build:
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
    - run: cargo install --path xbuild --root .
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.host }}-x
        path: bin/x${{ matrix.host == 'windows-latest' && '.exe' || '' }}

  # Github doesn't have runners for anything but 64 bit
  build-32bit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hecrj/setup-rust-action@v1
      with:
        targets: "i686-unknown-linux-gnu"
    - name: multilib
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install gcc-multilib libssl-dev:i386
    - run: cargo install --path xbuild --root . --target i686-unknown-linux-gnu
      env:
        OPENSSL_LIB_DIR: /usr/lib/i386-linux-gnu/
        OPENSSL_INCLUDE_DIR: /usr/include/openssl/

    - uses: actions/upload-artifact@v3
      with:
        name: i686-x
        path: bin/x

  build-template:
    strategy:
      fail-fast: false
      matrix:
        host:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        host-arch:
        - x86
        - x64
        opt:
        - debug
        - release
        target:
        - platform: linux
          arch: x86
        - platform: linux
          arch: x64
        - platform: macos
          arch: x64
        - platform: windows
          arch: x64
        - platform: android
          arch: arm64
        - platform: ios
          arch: arm64

    runs-on: ${{ matrix.host }}
    needs: [build, build-32bit]
    steps:
    - name: install rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable

    - name: install x
      if: ${{ matrix.host-arch == 'x64' }}
      uses: actions/download-artifact@v3
      with:
        name: ${{ matrix.host }}-x

    - name: install x i686
      if: ${{ matrix.host-arch == 'x86' }}
      uses: actions/download-artifact@v3
      with:
        name: i686-x

    - run: chmod +x ./x
      if: ${{ matrix.host == 'ubuntu-latest' || matrix.host == 'macos-latest' }}

    - name: install llvm ubuntu
      if: ${{ matrix.host == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install llvm

    - name: install llvm macos
      if: ${{ matrix.host == 'macos-latest' }}
      run: |
        brew install llvm
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: install java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11

    - name: install linux dependencies
      if: ${{ matrix.host == 'ubuntu-latest' }}
      run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev libgtk-3-dev squashfs-tools

    - name: install dependencies for i686
      if: ${{ matrix.host == 'ubuntu-latest' }}
      run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev:i386 libgtk-3-dev:i386 squashfs-tools:i386 libssl3:i386 gcc-multilib libglib2.0-0:i386

    - name: create project
      if: ${{ !((matrix.host == 'macos-latest' || matrix.host == 'windows-latest') && matrix.host-arch == 'x86') }}
      run: ./x new template
      
    # only linux can target linux as it is not clear what that even is exactly
    # glibc/musl gtk/qt x11/wayland
    # windows doesn't support posix symlinks so can't cross compile to macos/ios
    - name: build project
      if: >
        ${{
          !(matrix.host-arch == 'x64' && matrix.target.arch == 'x86' ||
            matrix.host == 'macos-latest' && matrix.host-arch == 'x86' ||
            matrix.host == 'windows-latest' && matrix.host-arch == 'x86' ||
            matrix.host == 'macos-latest' && matrix.target.platform == 'linux' ||
            matrix.host == 'windows-latest' && contains(fromJson('["linux", "macos", "ios"]'), matrix.target.platform)
          )
        }}    
      run: ../x build --platform ${{ matrix.target.platform }} --arch ${{ matrix.target.arch }} --${{ matrix.opt }}
      working-directory: template
      env:
        PKG_CONFIG_SYSROOT_DIR: "/"
